### PR TITLE
add property setter for netmask for IPNetwork()

### PR DESCRIPTION
**Pull request by nnathan**
This is a simple solution for #126 (but still unfinished).

```
In [1]: from netaddr.ip import IPNetwork

In [2]: x = IPNetwork('127.0.0.0/16')

In [3]: x.netmask = '255.255.255.0'

In [4]: x
Out[4]: IPNetwork('127.0.0.0/24')

In [5]: x.prefixlen
Out[5]: 24

In [6]: x.netmask
Out[6]: IPAddress('255.255.255.0')
```

Note: `x.netmask` can also be set with the same values as `prefixlen` e.g. `"24" and 24` are valid inputs.

I'll also add some tests and docs.

### CODE REVIEW

**Comment by nnathan** [comment]
(1) setting `netmask` property now supports both IPv4 and IPv6 netmasks
(2) added tests
(3) added docs

**Comment by drkjam** [comment]
Please refresh and re-submit this pull request for consideration as it currently has merge conflicts.

**Comment by nnathan** [comment]
Rebased on latest rel-0.7.x.

**Comment by drkjam** [comment]
I am tentative about this change due to possible Python version support issues (there are lots of users of this library and I have no good indication of what the minimum version of Python it is still being used on). 

I'd like to add it to the 0.8.0 milestone in case it causes unforeseen issues with some users (a breaking change would be more acceptable with the right version bump). Do you know which version of Python first introduced the setter syntax you make use of here?

**Comment by xpac1985** [comment]
The property.setter syntax was introduced with Python 2.6, released October 2008[1].
It has been in Python 3.0 from the beginning.

I would consider it safe to use something that old. 👍 

[1]https://docs.python.org/2.7/whatsnew/2.6.html#other-language-changes

**Comment by jstasiak** [comment]
Thank you! Just merged this into master as b08dcb6e72db.

**Pull request closed without merging**
