### PR TITLE
Fix for is_loopback behaviour (issue: #222)

### PR DESCRIPTION
**Pull request by nkeulen**

### CODE REVIEW

**Review by jstasiak — CHANGES_REQUESTED** [review]
Thank you, this looks sensible. Can you add a unit test or modify an existing one?

**Comment by nkeulen** [comment]
> 
> 
> Thank you, this looks sensible. Can you add a unit test or modify an existing one?

I've added a unit test file: `test_ip_network_categories.py`,
which mirrors what was done for IPAddress in `test_ip_categories.py` but for IPNetwork instead.

**Comment by jstasiak** [comment]
Just the `test_is_loopback` test would be enough, but thanks!

**Comment by jstasiak** [comment]
Released in version 0.9.0 today.

**Pull request merged**
